### PR TITLE
Play row on tap

### PR DESCRIPTION
**Pull request by irshadshalu**

### CODE REVIEW

**Comment by wcarss** [comment]
if you'd prefer, I can remake the play-row-on-tap-atop the current master, but if you want both play note on tap and play row, this seems good! Two things I didn't have in this commit were the cursor being set to pointer when over the button and animating the row to scale down on tap like it would when playing normally.

I'll be asleep for the next 10ish hours, so if you end up merging or remaking commits or whatever, that's all fine by me :)

**Comment by irshadshalu** [comment]
Yeah, I was busy too. 


I'm still on the fence about this one. On one side, it is a great feature addition, but on the other side, I'm unsure whether it makes it a bit confusing?. I'll ask around for some more user-feedback and let you know.

Btw, out of topic, your email is not reachable 

         Recipient address rejected: unverified address: Address verification in progress

**Comment by wcarss** [comment]
👍 getting some feedback from others to refine this/see if it's worth it sounds great!

that's very strange about my email, thanks for letting me know. I tried sending a few test messages over the past day and they got through. Maybe there was a temporary delivery issue 🤷 -- if you need it, another address that goes to the same box is carss.w @ google's consumer email provider

**Comment by irshadshalu** [comment]
> Two things I didn't have in this commit were the cursor being set to pointer when over the button and animating the row to scale down on tap like it would when playing normally.

Will you be adding this?

**Comment by wcarss** [comment]
ah, I hadn't planned to unless you wanted to move ahead with it. The row-animation wasn't working the way I'd expected it to, so I stopped trying until further news 😄

**Comment by irshadshalu** [comment]
I tried it and it seems like pretty useful for composing. Make sure the row click animation works as expected and we're good to go... I think, also, row play is only when you pause or all the time?

**Comment by wcarss** [comment]
:+1: cool, I'll look at this tomorrow. I had let the user do it at any time I think, on the basis of not having to communicate that the buttons are inactive under some conditions.

**Comment by irshadshalu** [comment]
Okay, I think thta will work too

**Comment by wcarss** [comment]
thanks for waiting a few days -- been tied up with projects :)

rebased this atop your most recent work and switched to use the font-awesome icon rather than the unicode play-symbol, and fixed the animation on-click:

**Comment by irshadshalu** [comment]
Looking good. looks like no conflicts as well. I will merge and deploy.

**Pull request merged**
