### PR TITLE
Play note on click when player is paused.

### LINKED ISSUE #20: Play note on click
Playing the note on click when adding it would make writing much easier, especially for long tunes.  This way the user doesn't have to wait for it to look around to the bit they just played to listen to how it sounds.

Also neat website!

### PR DESCRIPTION
**Pull request by irshadshalu**
This will fix #20

### CODE REVIEW

**Comment by irshadshalu** [comment]
@wcarss  what do you think?, Some changes will be needed after #24 .

**Comment by wcarss** [comment]
👍 to needing some change to the note play bit after #24 merges

I see better now what you meant in the issue thread about it feeling a little bit clunky. It's not possible to just 'hit' a note and sample it -- hearing it means turning it on, and then if you didn't like it, you have to turn it back off. Without introducing some kind of a 'mode' to enable that, it seems hard to escape.

One thing that might mitigate the feeling of slowness in turning things on/off while experimenting with the sound is reducing the activation transition time from 0.1s maybe to e.g. 0.03s, which should still be pretty but below the perceptible wait-level. Or even removing the transition on deactivate, to make it feel that much snappier and less like you're waiting for things to turn off. Just thoughts, though!

As far as the code, it looks good to me.

**Comment by irshadshalu** [comment]
> hearing it means turning it on, and then if you didn't like it, you have to turn it back off

This is why I thought of having a dedicated row just to sample notes, but then it adds an unnecessary layer of complexity and makes it a bit more confusing. So that's not an option.


> Without introducing some kind of a 'mode' to enable that 

I think playCell on pause is good enough, because when someone has paused and is composing manually, a feedback is better than nothing. 


> transition time from 0.1s maybe to e.g. 0.03s 

I agree. Let's make it 0.06, we want to give the feeling of turning on light too.

> Or even removing the transition on deactivate

I think the turning on and off should be done in the same manner, or it will feel odd, so let's go with 0.06

**Comment by irshadshalu** [comment]
Thinking about it, now I'm confused whether or not to merge this, because a user might

1. Come into the site for the first time.
2. Click on tiles randomly and listen to the sound (because it will be paused. by default)
3. Leave, without actually hitting the play button because he/she might think "This is just it!" 


I think we should avoid this. From most of the feedback I got, the fun part of the app was in seeing your composition progress over time and the sense of creating something beautiful, we might ruin it for someone with this change.

**Comment by wcarss** [comment]
hmmm, what about play on hover?

**Comment by irshadshalu** [comment]
Again, the same issue.

 we don't want users to navigate away without actually hitting Play and making something that sounds good. 

Also, resulting sounds from a hover are bad as I move and hear all the clings.. try clicking and dragging your mouse to get that effect.

**Comment by irshadshalu** [comment]
Maybe once we have mode support (as in #12), we can add a mode called sandbox where user can just tap and play)

**Comment by wcarss** [comment]
I don't feel people are particularly likely to arrive and not understand what to do because it's already made sounds, especially when there is a Play button already. The issue was looking for help on giving audio-feedback while composing rather than having to wait for the row to loop to whatever you're making, which (as a user) I also experienced!

What about a small play-button to the left or right of each row, that on click would play just that row? You could preview chords or individual notes pretty easily and could style it unobtrusively so people don't mistake it for a note itself

**Comment by wcarss** [comment]
I've trial-implemented a rough version of the play-row-on-tap in this branch on my fork: https://github.com/irshadshalu/music-grid/compare/master...wcarss:play_row_on_tap?expand=1

**Comment by wcarss** [comment]
(as a user report, having this play-a-row button made me go from not wanting to make a longer composition to comfortably making [this](https://music-grid.surge.sh/#0-1152-176-1152-1344-1448-1448-1448-1344-1152-2560-1152-1344-1448-1448-1448-0-1152-1344-1448-1448-724-724-724-1152-1344-1448-1448-1448-724-724-724-0-1152-160-1152-2560-1152-640-288-160-1152-2560-1152-1344-1448-1448-1448-0-2304-2560-1152-1344-1448-1448-1448-1344-1152-2560-1152-1344-1448-1448-1448-&200) pretty quickly!)

**Comment by irshadshalu** [comment]
This looks good!. Do you feel this is better for helping with composition than play cell on tap?. Do raise a PR :)

**Comment by irshadshalu** [comment]
I put a start playing for the very first time user clicks on any cell. I think this will clear up the confusion and will get a new user start going :) Merging this PR.

**Comment by wcarss** [comment]
ah, interesting idea!

**Pull request merged**
